FROM ubuntu:22.04

RUN apt-get update && \
    apt-get -y upgrade && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
        gcc \
        git \
        g++ \
        make \
        automake \
        file
