name: Run on Linux

on:
  pull_request:
    branches:
      - '**'

jobs:
  Linux:

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install zlib1g-dev make

    - uses: actions/checkout@v1

    - name: run CI script
      run: ./SpecSAT.py -d

