name: Run on Linux

on:
  pull_request:
    branches:
      - '**'

jobs:
  Linux:

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install make python3-setuptools sudo zlib1g-dev

    - uses: actions/checkout@v1

    - name: get python modules
      run: python3 -m pip install --upgrade --user -U -r requirements.txt

    - name: run CI script
      run: ./SpecSAT.py -d

