name: Run on Mac OS

on:
  pull_request:
    branches:
      - '**'

jobs:
  MacOS:

    runs-on: macos-latest

    steps:
    - name: Install Packages
      run: brew install libzip python

    - name: get pip
      run: python -m pip install --user --upgrade pip

    - uses: actions/checkout@v1

    - name: get venv
      run: python -m pip install --user virtualenv

    - name: run CI script
      run: ./SpecSAT.sh -d -u
