name: Run on Mac OS

on:
  pull_request:
    branches:
      - '**'

jobs:
  MacOS:

    runs-on: macos-latest

    steps:
    - name: Install Packages
      run: brew install libzip

    - uses: actions/checkout@v1

    - name: run CI script
      run: ./SpecSAT.py -d
